=== sandokanCat/cv/server/form.dtd
<!ELEMENT form (field+)>
<!ATTLIST form action ID #REQUIRED>
<!ATTLIST form method ID #REQUIRED>
<!ATTLIST form enctype ID #REQUIRED>
<!ELEMENT field (name, type, label)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT label (#PCDATA)>

=== sandokanCat/cv/server/form.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form SYSTEM "form.dtd">

<form action="./_secure/mail.php" method="POST" enctype="text/plain">
    <field>
        <name>name</name>
        <type>text</type>
        <label>Nombre:</label>
    </field>
    <field>
        <name>email</name>
        <type>email</type>
        <label>Correo Electr√≥nico:</label>
    </field>
    <field>
        <name>subject</name>
        <type>text</type>
        <label>Asunto:</label>
    </field>
    <field>
        <name>content</name>
        <type>textarea</type>
        <label>Mensaje:</label>
    </field>
    <!-- <field>
        <name>consent</name>
        <type>checkbox</type>
        <label>Consentimiento</label>
    </field> -->
    <field>
        <name>send</name>
        <type>submit</type>
        <label>Enviar</label>
    </field>
</form>
